"""create_journal

Revision ID: 7e4dc5a68978
Revises: 88700fbd1708
Create Date: 2026-10-06 15:25:48.632730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4dc5a68978'
down_revision: Union[str, Sequence[str], None] = '88700fbd1708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('help_messages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('user_id_fk', 'help_messages', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.add_column('lie_acts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('user_id_fk', 'lie_acts', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.add_column('operation_acts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('user_id_fk', 'operation_acts', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.add_column('reaction_plans', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('user_id_fk', 'reaction_plans', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.add_column('reaction_plans_history', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('user_id_fk', 'reaction_plans_history', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_id_fk', 'reaction_plans_history', type_='foreignkey')
    op.drop_column('reaction_plans_history', 'user_id')
    op.drop_constraint('user_id_fk', 'reaction_plans', type_='foreignkey')
    op.drop_column('reaction_plans', 'user_id')
    op.drop_constraint('user_id_fk', 'operation_acts', type_='foreignkey')
    op.drop_column('operation_acts', 'user_id')
    op.drop_constraint('user_id_fk', 'lie_acts', type_='foreignkey')
    op.drop_column('lie_acts', 'user_id')
    op.drop_constraint('user_id_fk', 'help_messages', type_='foreignkey')
    op.drop_column('help_messages', 'user_id')
    # ### end Alembic commands ###
