"""adding indexis

Revision ID: 03b0f37ebb56
Revises: 346cce857adc
Create Date: 2026-09-26 08:34:58.237793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b0f37ebb56'
down_revision: Union[str, Sequence[str], None] = '346cce857adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_help_messages_datetime'), 'help_messages', ['datetime'], unique=False)
    op.create_index(op.f('ix_reaction_plans_history_change_datetime'), 'reaction_plans_history', ['change_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reaction_plans_history_change_datetime'), table_name='reaction_plans_history')
    op.drop_index(op.f('ix_help_messages_datetime'), table_name='help_messages')
    # ### end Alembic commands ###
