"""create_soursec

Revision ID: e4ad537663df
Revises: 2b8097fcd639
Create Date: 2026-10-06 10:06:31.810986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4ad537663df'
down_revision: Union[str, Sequence[str], None] = '2b8097fcd639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('STATION', 'SHIP', 'EXPEDITION', 'AIRCRAFT', name='sourse_type'), nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=7, scale=4), nullable=False),
    sa.Column('longitude', sa.NUMERIC(precision=7, scale=4), nullable=False),
    sa.Column('need_check', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.CheckConstraint('latitude >= -180.0 AND latitude <= 180.0', name='latitude_ck'),
    sa.CheckConstraint('longitude >= -180.0 AND longitude <= 180.0', name='longitude_ck'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('help_messages', sa.Column('sourse_id', sa.Integer(), nullable=False))
    op.create_foreign_key('source_id_fk', 'help_messages', 'sources', ['sourse_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_column('help_messages', 'latitude')
    op.drop_column('help_messages', 'longitude')
    op.drop_column('help_messages', 'source_type')
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE OR REPLACE FUNCTION insert_update_reaction_plans()
        RETURNS trigger AS $$
        DECLARE
            source_latitude NUMERIC(7, 4);
            source_longitude NUMERIC(7, 4);
            device_latitude NUMERIC(7, 4);
            device_longitude NUMERIC(7, 4);
            device_status VARCHAR;
            device_type VARCHAR;
            help_message_status VARCHAR;
            device_reach_zone_km NUMERIC(20, 2);
            help_call_time TIMESTAMP;
        BEGIN

            SELECT help_messages.status, help_messages.datetime, sources.latitude, sources.longitude INTO help_message_status, help_call_time, source_latitude, source_longitude
            FROM help_messages
            JOIN sources ON sources.id = help_messages.sourse_id
            WHERE help_messages.id = NEW.help_message_id;

            IF (help_message_status = 'COMPLETED' OR help_message_status = 'FALSE_ALARM') THEN
                RAISE 'This help message already done';
            END IF;
            
            IF (help_call_time > NEW.planning_time) THEN
                RAISE 'Planning time smaller than help call time';
            END IF;

            SELECT lifesaving_devices.latitude, lifesaving_devices.longitude, lifesaving_devices.status, lifesaving_devices.type, lifesaving_devices.reach_zone_km
            INTO device_latitude, device_longitude, device_status, device_type, device_reach_zone_km
            FROM lifesaving_devices
            WHERE lifesaving_devices.id = NEW.lifesaving_devices_id;

            IF TG_OP = 'INSERT' THEN
            IF (device_status = 'ON_MISSION') OR (device_status = 'UNDER_MAINTENANCE') THEN
                RAISE EXCEPTION 'Lifesaving devices cannot be used for this operation, because its status is %', device_status;
            END IF;
            ELSIF TG_OP = 'UPDATE' THEN
            IF (device_status = 'ON_MISSION' AND OLD.lifesaving_devices_id != NEW.lifesaving_devices_id) OR (device_status = 'UNDER_MAINTENANCE') THEN
                RAISE EXCEPTION 'Lifesaving devices cannot be used for this operation, because its status is %', device_status;
            END IF;
            END IF;

            IF (device_type = 'HELICOPTER' AND ('SNOWFALL' = ANY(NEW.weather_condition) OR 'BLIZZARD' = ANY(NEW.weather_condition) OR 'STRONG_WINDS' = ANY(NEW.weather_condition))) THEN
            RAISE EXCEPTION 'Lifesaving devices cannot be used for this operation, because its type is helicopter and we have bad weather in reaction plan information';
            END IF;

            IF (haversine_km(source_latitude, source_longitude, device_latitude, device_longitude) > device_reach_zone_km) THEN
            RAISE EXCEPTION 'Lifesaving devices cannot be used for this operation, because it has small reach zone for this operation';
            END IF;

            UPDATE lifesaving_devices
            SET status = 'ON_MISSION'
            WHERE id = NEW.lifesaving_devices_id;

            IF TG_OP = 'UPDATE' THEN
            IF NEW.lifesaving_devices_id != OLD.lifesaving_devices_id THEN
                UPDATE lifesaving_devices
                SET status = 'READY'
                WHERE id = OLD.lifesaving_devices_id;
            END IF;
            END IF;

            IF TG_OP = 'INSERT' THEN
            UPDATE help_messages
            SET status = 'IN_PROGRESS'
            WHERE id = NEW.help_message_id;
            END IF;
            
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION change_source_check_need()
        RETURNS trigger AS $$
        DECLARE
            lie_act_count INT;
            source_id INT;
        BEGIN
            SELECT sources.id INTO source_id
            FROM sources
            JOIN help_messages ON sources.id = help_messages.sourse_id
            WHERE help_messages.id = NEW.help_message_id;

            SELECT COUNT(*) INTO lie_act_count
            FROM lie_acts
            JOIN help_messages ON help_messages.id = lie_acts.help_message_id
            JOIN sources ON sources.id = help_messages.sourse_id
            WHERE sources.id = source_id
                AND
                    lie_acts.fact_datetime >= DATE_TRUNC('quarter', CURRENT_DATE)
                AND 
                    lie_acts.fact_datetime <  DATE_TRUNC('quarter', CURRENT_DATE) + INTERVAL '3 months';
            
            IF lie_act_count > 5 THEN
                UPDATE sources
                SET need_check = TRUE
                WHERE sources.id = source_id;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    op.execute(
        """
        CREATE TRIGGER check_source
        AFTER INSERT ON lie_acts
        FOR EACH ROW
        EXECUTE FUNCTION change_source_check_need();
        """
    )
    





def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('help_messages', sa.Column('source_type', postgresql.ENUM('STATION', 'SHIP', 'EXPEDITION', 'AIRCRAFT', name='sourse_type'), autoincrement=False, nullable=False))
    op.add_column('help_messages', sa.Column('longitude', sa.NUMERIC(precision=7, scale=4), autoincrement=False, nullable=False))
    op.add_column('help_messages', sa.Column('latitude', sa.NUMERIC(precision=7, scale=4), autoincrement=False, nullable=False))
    op.drop_constraint('source_id_fk', 'help_messages', type_='foreignkey')
    op.drop_column('help_messages', 'sourse_id')
    op.drop_table('sources')
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE OR REPLACE FUNCTION insert_update_reaction_plans()
        RETURNS trigger AS $$
        DECLARE
            help_call_latitude NUMERIC(7, 4);
            help_call_longitude NUMERIC(7, 4);
            device_latitude NUMERIC(7, 4);
            device_longitude NUMERIC(7, 4);
            device_status VARCHAR;
            device_type VARCHAR;
            help_message_status VARCHAR;
            device_reach_zone_km NUMERIC(20, 2);
            help_call_time TIMESTAMP;
        BEGIN

            SELECT help_messages.status, help_messages.latitude, help_messages.longitude, help_messages.datetime INTO help_message_status, help_call_latitude, help_call_longitude, help_call_time
            FROM help_messages
            WHERE help_messages.id = NEW.help_message_id;

            IF (help_message_status = 'COMPLETED' OR help_message_status = 'FALSE_ALARM') THEN
            RAISE 'This help message already done';
            END IF;
            
            IF (help_call_time > NEW.planning_time) THEN
                RAISE 'Planning time smaller than help call time';
            END IF;

            SELECT lifesaving_devices.latitude, lifesaving_devices.longitude, lifesaving_devices.status, lifesaving_devices.type, lifesaving_devices.reach_zone_km
            INTO device_latitude, device_longitude, device_status, device_type, device_reach_zone_km
            FROM lifesaving_devices
            WHERE lifesaving_devices.id = NEW.lifesaving_devices_id;

            IF TG_OP = 'INSERT' THEN
            IF (device_status = 'ON_MISSION') OR (device_status = 'UNDER_MAINTENANCE') THEN
                RAISE EXCEPTION 'Lifesaving devices cannot be used for this operation, because its status is %', device_status;
            END IF;
            ELSIF TG_OP = 'UPDATE' THEN
            IF (device_status = 'ON_MISSION' AND OLD.lifesaving_devices_id != NEW.lifesaving_devices_id) OR (device_status = 'UNDER_MAINTENANCE') THEN
                RAISE EXCEPTION 'Lifesaving devices cannot be used for this operation, because its status is %', device_status;
            END IF;
            END IF;

            IF (device_type = 'HELICOPTER' AND ('SNOWFALL' = ANY(NEW.weather_condition) OR 'BLIZZARD' = ANY(NEW.weather_condition) OR 'STRONG_WINDS' = ANY(NEW.weather_condition))) THEN
            RAISE EXCEPTION 'Lifesaving devices cannot be used for this operation, because its type is helicopter and we have bad weather in reaction plan information';
            END IF;

            IF (haversine_km(help_call_latitude, help_call_longitude, device_latitude, device_longitude) > device_reach_zone_km) THEN
            RAISE EXCEPTION 'Lifesaving devices cannot be used for this operation, because it has small reach zone for this operation';
            END IF;

            UPDATE lifesaving_devices
            SET status = 'ON_MISSION'
            WHERE id = NEW.lifesaving_devices_id;

            IF TG_OP = 'UPDATE' THEN
            IF NEW.lifesaving_devices_id != OLD.lifesaving_devices_id THEN
                UPDATE lifesaving_devices
                SET status = 'READY'
                WHERE id = OLD.lifesaving_devices_id;
            END IF;
            END IF;

            IF TG_OP = 'INSERT' THEN
            UPDATE help_messages
            SET status = 'IN_PROGRESS'
            WHERE id = NEW.help_message_id;
            END IF;
            
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    op.execute("DROP FUNCTION change_source_check_need;")
    op.execute("DROP TRIGGER check_source ON lie_acts;")

    