class DeletedUserException(Exception):
    ...

class IncorrectUserRole(Exception):
    ...

class FailedLoginException(Exception):
    ...

class SuperuserChangeException(Exception):
    ...

class NotFoundRecordException(Exception):
    ...