class DeletedUserException(Exception):
    ...

class IncorrectUserRole(Exception):
    ...

class FailedLoginException(Exception):
    ...

class DeleteSuperuserException(Exception):
    ...

class NotFoundRecordException(Exception):
    ...